default: &default
  adapter: postgresql
  database: <%= ENV['POSTGRES_DATABASE'] || "docker-testing_#{ENV['RAILS_ENV']}" %>
  encoding: unicode
  host:     <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  port:     <%= ENV['POSTGRES_PORT'] || 5432 %>
  username: <%= ENV['POSTGRES_USERNAME'] || 'root' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
